# AlertManager configuration for AI Fundamentals
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ai-fundamentals.local'
  smtp_auth_username: ''
  smtp_auth_password: ''

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Warning alerts - grouped notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
    
    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 24h

# Inhibition rules to prevent spam
inhibit_rules:
  # Inhibit info alerts when warning alerts are firing
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'service']
  
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

# Receivers configuration
receivers:
  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@ai-fundamentals.local'
        subject: '[CRITICAL] AI Fundamentals Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
        headers:
          Priority: 'high'
    
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert'
            password: 'webhook123'

  # Warning alerts - email only
  - name: 'warning-alerts'
    email_configs:
      - to: 'team@ai-fundamentals.local'
        subject: '[WARNING] AI Fundamentals Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}

  # Info alerts - digest format
  - name: 'info-alerts'
    email_configs:
      - to: 'monitoring@ai-fundamentals.local'
        subject: '[INFO] AI Fundamentals Daily Digest'
        body: |
          Daily Alert Summary:
          {{ range .Alerts }}
          - {{ .Annotations.summary }} ({{ .Labels.service }})
          {{ end }}

# Slack integration (commented out - configure as needed)
# - name: 'slack-alerts'
#   slack_configs:
#     - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#       channel: '#ai-fundamentals-alerts'
#       title: 'AI Fundamentals Alert'
#       text: |
#         {{ range .Alerts }}
#         *Alert:* {{ .Annotations.summary }}
#         *Description:* {{ .Annotations.description }}
#         *Service:* {{ .Labels.service }}
#         *Severity:* {{ .Labels.severity }}
#         {{ end }}
#       send_resolved: true

# PagerDuty integration (commented out - configure as needed)
# - name: 'pagerduty-alerts'
#   pagerduty_configs:
#     - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
#       description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
#       details:
#         summary: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
#         description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
#         severity: '{{ .GroupLabels.severity }}'