apiVersion: v1
kind: Namespace
metadata:
  name: ai-fundamentals
  labels:
    name: ai-fundamentals
    environment: production
    app.kubernetes.io/name: ai-fundamentals
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: ai-fundamentals-platform
  annotations:
    description: "Namespace for AI Fundamentals application"