apiVersion: v1
kind: Secret
metadata:
  name: ai-fundamentals-secrets
  namespace: ai-fundamentals
  labels:
    app.kubernetes.io/name: ai-fundamentals
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: ai-fundamentals-platform
type: Opaque
data:
  # Base64 encoded secrets
  # To encode: echo -n "your-secret-value" | base64
  # To decode: echo "encoded-value" | base64 -d
  
  # OpenAI API Key (replace with actual base64 encoded value)
  OPEN_AI_API_KEY: "REPLACE_WITH_BASE64_ENCODED_OPENAI_API_KEY"
  
  # JWT Secret for authentication (if used)
  JWT_SECRET: "REPLACE_WITH_BASE64_ENCODED_JWT_SECRET"
  
  # Database password (if database is used)
  DATABASE_PASSWORD: "REPLACE_WITH_BASE64_ENCODED_DB_PASSWORD"
  
  # Redis password (if Redis is used)
  REDIS_PASSWORD: "REPLACE_WITH_BASE64_ENCODED_REDIS_PASSWORD"
  
  # Encryption key for sensitive data
  ENCRYPTION_KEY: "REPLACE_WITH_BASE64_ENCODED_ENCRYPTION_KEY"

---
# Example of how to create secrets using kubectl:
# kubectl create secret generic ai-fundamentals-secrets \
#   --from-literal=OPEN_AI_API_KEY="your-openai-api-key" \
#   --from-literal=JWT_SECRET="your-jwt-secret" \
#   --from-literal=DATABASE_PASSWORD="your-db-password" \
#   --from-literal=REDIS_PASSWORD="your-redis-password" \
#   --from-literal=ENCRYPTION_KEY="your-encryption-key" \
#   --namespace=ai-fundamentals